### ISSUE TITLE
Engaging with individuals

### ISSUE THREAD

**Issue by mrichardsJBOIT** [Roakz/myCitySubscription#4]
Homelessness is often a result of many many external factors such as family issues, unforeseen personal disaster, lack of support networks, physical and mental health issues, etc, etc.  I would like to suggest the design is extended so that the homeless person and the person making the subscription have the opportunity to interact with each other.  
Often it's the case big issue sellers stay in one area and the interaction of selling and being able to buy more magazines to sell, creates a routine and motivation to keep moving forward.
It would be a shame to miss the opportunity to create a personal connection and which could have massive positive change on someones day.

**Comment by Roakz** [comment]
Thanks for the input...At this stage, I'm waiting for some feedback from some organizations that deal specifically with this kind of stuff and have had some ideas thrown in the ring from some other people looking to contribute in order to still provide a way to do this manual transaction so as not to end up being completely un personal for lack of better phrasing. 

I feel also that what your saying is important which is why something like myCitySubscription would be built this in mind and have the additional fancy features to help increase potential profits for those who may not be comfortable engaging or are simply too busy but also still want to contribute. 

At the end of the day, it will always be a controversial subject within the community. But I truly appreciate feedback like this and please bear in mind that all of this is being done for the right reasons by people who genuinely want to help and try their best to contribute to improving people's lives.

ultimately more money raised means more potential for non-for-profit support networks and things as well...It's not to say that we can eradicate the fact that people find themselves in these hard situations. But we can certainly try our best to help people when they are in need.

**Comment by Roakz** [comment]
p.s I am no expert in this stuff...just a guy that wants to help make things better for people...fellow humans who might need help more than I do. Feedback appreciated and further research will ensue!

**Comment by mrichardsJBOIT** [comment]
I'm keen to be involved, from little things big things grow!

**Comment by Roakz** [comment]
I'm glad to hear! hopefully we'll have some more documentation etc soon and start pushing some stuff up. Please keep the feedback coming during the planning and documentation phase!
